enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Spotify]
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.spotify.music"
build-mode = "apk"
patcher-args = """\
	-backgroundColor=#141415 \
	-overridePlayerGradientColor=false \
	-backgroundColorSecondary=#252530 \
	-accentColor=#6e94b2 \
	-accentColorPressed=#6e94b255 \
"""
included-patches = "'Custom theme'"
